# Generated by Django 3.2.5 on 2024-01-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='cloth.Tag'),
        ),
    ]
