# Generated by Django 5.0 on 2023-12-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите названия фильма')),
                ('description', models.TextField(blank=True, verbose_name='Описание фильма')),
                ('image', models.ImageField(blank=True, upload_to='films/', verbose_name='Фото фильма')),
                ('price', models.PositiveIntegerField(blank=True, verbose_name='Укажите цену фильма')),
                ('genre', models.CharField(choices=[('Драма', 'Драма'), ('Мелодрама', 'Мелодрама'), ('Боевик', 'Боевик'), ('Вестерн', 'Вестерн'), ('Фэнтези', 'Фэнтези'), ('Исторические', 'Исторические')], max_length=100)),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор фильма')),
                ('trailer', models.URLField(verbose_name='Ссылка на трейлер')),
            ],
        ),
    ]
