# Generated by Django 5.0 on 2023-12-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='genre',
            field=models.CharField(choices=[('Драма', 'Драма'), ('Мелодрама', 'Мелодрама'), ('Боевик', 'Боевик'), ('Вестерн', 'Вестерн'), ('Фэнтези', 'Фэнтези'), ('Исторические', 'Исторические'), ('Комедия', 'Комедия')], max_length=100),
        ),
    ]
