# Generated by Django 5.0 on 2023-12-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Cars',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='book_creation_date',
            new_name='cars_creation_date',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='book_description',
            new_name='cars_description',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='book_image',
            new_name='cars_image',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='book_name',
            new_name='cars_name',
        ),
    ]
