# Generated by Django 5.0 on 2023-12-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_books_cars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='cars_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
